### ISSUE TITLE
Quirks when using `class`/`className` in JSX

### ISSUE THREAD

**Issue by jcfranco** [AFASSoftware/maquette-typescript-jsx-starter#1]
When using `className` in JSX, maquette throws an error stating to use `class` instead. Doing so works, but I can't get the compiled output to quote `class` since quoting attributes in JSX doesn't seem to be valid. 

Do you have any suggestions to produce a quoted `class` in the compiled output?

**Comment by johan-gorter** [comment]
I am not sure what you mean by this. If I take the jsx starter application and change a line to 

```
<p class="output quote-needed">
```

Then everything works fine. The compiled Javascript looks like

```
{ 'class': 'output quote-needed' }
```

This looks fine to me. Can you please explain the issue that you are having in more detail?

**Comment by jcfranco** [comment]
I apologize for not adding more detail before. 

This came up from a separate project using a custom JSX factory with TypeScript's `--reactNamespace` option (i.e., no Babel). In this workflow, `class` isn't quoted when compiled. 

I'll create an issue in the TypeScript repo, since it looks like `class` and `for` would need to be treated differently since they are valid JSX attributes, but reserved words when compiled. 

Thanks!

**Comment by johan-gorter** [comment]
I believe that the word 'class' does not even need to be quoted in Javascript when used as a key in an object literal, so the following code should still be valid in Javascript:

```
h('div', {class: 'output quote-needed'})
```

Please let me know if you have any success with `--reactNamespace`, so I can update the article

**Comment by jcfranco** [comment]
You are correct – [Reserved word usage](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords). Related: https://github.com/Microsoft/TypeScript/issues/9827#issuecomment-238322436

`--reactNamespace` + custom JSX factory works like a charm, by the way.
